### ISSUE TITLE
Do not compile on MacOS 10.14.3, Apple LLVM version 10.0.0 (clang-1000.11.45.5)

### ISSUE THREAD

**Issue by oleg-kachan** [blas-lapack-rs/blas#31]
I'm trying to compile gemm example from crate page and it gives me error:

```
error: linking with "cc" failed: exit code: 1

 = note: Undefined symbols for architecture x86_64:
            "_dgemm_", referenced from:
                blas::dgemm::hea1ad9439b9f3ae2 in hello_cargo-e34d1495f2dabfc9.47k295ih7vv0tck5.rcgu.o
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by IvanUkhov** [comment]
Hi, thanks for the issue. Can you please post the whole example?

**Comment by oleg-kachan** [comment]
> main.rs

```
use blas::*;

fn main() {

    let (m, n, k) = (2, 4, 3);
    let a = vec![
        1.0, 4.0,
        2.0, 5.0,
        3.0, 6.0,
    ];
    let b = vec![
        1.0, 5.0,  9.0,
        2.0, 6.0, 10.0,
        3.0, 7.0, 11.0,
        4.0, 8.0, 12.0,
    ];
    let mut c = vec![
        2.0, 7.0,
        6.0, 2.0,
        0.0, 7.0,
        4.0, 2.0,
    ];

    unsafe {
        dgemm(b'N', b'N', m, n, k, 1.0, &a, m, &b, k, 1.0, &mut c, m);
    }

    assert!(
        c == vec![
            40.0,  90.0,
            50.0, 100.0,
            50.0, 120.0,
            60.0, 130.0,
        ]
    );
}
```

> Cargo.toml dependencies section

```
[dependencies]
blas = "0.20.0"
openblas-src = "0.7.0"
```

**Comment by IvanUkhov** [comment]
I think the linking is missing as `openblas-src` is not mentioned in the code. Please take a look at the example [here](https://github.com/blas-lapack-rs/blas-lapack-rs.github.io/wiki).

**Comment by oleg-kachan** [comment]
Thank you!

It was a really stupid question from Rust newbie.

**Comment by IvanUkhov** [comment]
No problem at all!
